In [18]:
import numpy as np
import cv2

In [19]:
x = np.ones([3,3])
x[0][:] = 0
x[2][:] = 0
x = x/np.sum(x)

In [20]:
y = np.random.randn(10,10)
y = np.uint8(y*255)
y[y>120] =255
y[y<=120] = 0
y

array([[  0, 255, 255,   0, 255,   0, 255,   0, 255,   0],
       [  0, 255, 255, 255, 255, 255,   0,   0,   0,   0],
       [255, 255, 255, 255, 255,   0,   0, 255,   0, 255],
       [  0, 255,   0,   0, 255, 255, 255,   0,   0,   0],
       [  0, 255, 255,   0, 255,   0, 255,   0, 255, 255],
       [  0, 255, 255,   0, 255, 255, 255,   0, 255, 255],
       [255, 255, 255,   0, 255, 255,   0, 255,   0,   0],
       [255, 255, 255, 255, 255,   0, 255, 255,   0,   0],
       [255,   0, 255, 255, 255, 255, 255,   0,   0,   0],
       [255, 255,   0, 255,   0, 255,   0,   0, 255, 255]], dtype=uint8)

In [29]:
t = cv2.filter2D(y,-1,x)
t[t>120] =255
t[t<=120] = 0
t
sum(t)

array([247, 247, 247, 248, 248, 248, 251, 252, 252, 252], dtype=uint8)

In [27]:
t[0] = 0
t[1][0:4]=0
a = np.where(t>254)
a

(array([1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7,
        7, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9], dtype=int64),
 array([4, 5, 0, 1, 2, 3, 4, 8, 0, 4, 5, 6, 0, 1, 2, 3, 5, 7, 8, 9, 0, 1,
        2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6,
        7, 1, 2, 3, 4, 5, 6, 0, 1, 2, 4, 8, 9], dtype=int64))

In [34]:
line_mid_x = int(np.mean(a[0]))
line_mid_y = np.sum(a[1])
line_mid_x

5

In [35]:
is_white = t==0
is_white

array([[False, False, False, False,  True, False,  True, False,  True,
        False],
       [False, False, False, False, False, False,  True,  True,  True,
         True],
       [False, False, False, False, False,  True,  True,  True, False,
         True],
       [False,  True,  True,  True, False, False, False,  True,  True,
         True],
       [False, False, False, False,  True, False,  True, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False,  True,  True,
         True],
       [False, False, False, False, False, False, False, False,  True,
         True],
       [ True, False, False, False, False, False, False,  True,  True,
         True],
       [False, False, False,  True, False,  True,  True,  True, False,
        False]])

In [36]:
np.sum(is_white==0)

68